# An example of ClusterConfig showing managed nodegroups
# Change the subnet id from your account
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-59120577 }
      us-east-1b: { id: subnet-67b9612a }
      us-east-1c: { id: subnet-1c786d40 }

metadata:
    name: my-k8s-cluster
    region: us-east-1
    version: "1.18"

managedNodeGroups:
  - name: my-node-group
    instanceType: t2.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
